version: '3'

services:
    catalog:
        image: postgres:16
        environment:
            - POSTGRES_PASSWORD=testpassword
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_INITDB_ARGS="--auth=trust"
        command: "-c password_encryption=md5"

    irods-catalog-provider:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - catalog
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir

    irods-catalog-consumer:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - irods-catalog-provider
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir

# This volume is mounted on all test servers for detached mode testing which
# requires a common vault.
volumes:
    shared_volume:
